### ISSUE TITLE
29. In the test class create a method getAllQuizzesReturnsEmptyListWhenNoQuizzesExist. Send a request without saving a quiz to the database. Then, the response should have an empty list

### ISSUE THREAD

**Issue by madaraDance** [https-github-com-DenisHki/quizzer_app#159]

**Comment by padwhen** [comment]
This task is contradictory. The majority of controllers in this project will return a thymeleaf file, so it is impossible to return an empty array. Moreover, sending a GET will basically return anything without a request with it. So I divide this task into 2 smaller tasks:
1. Mock data, so when test getAllQuizzesReturnsANotificationWhenNoQuizzesExist run, it will delete all the data. I also add a condition in "quizzesList.html", that if there is no quiz, it will display "No data in the database". So when the test is run, it will check in the HTML file if "No data in the database" exists.
2. POST a quiz data will return an error code/response. By modifying the controller saveQuiz first. Test will be postQuizWillReturnAnError



![Image](https://github.com/https-github-com-DenisHki/quizzer_app/assets/123895854/20b66fba-3284-427c-a8b6-5eae82603d83)
